apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dynamodb-t1-vs
spec:
  hosts:
  - "*"
  gateways:
  - jstore-gateway
  http:
  - match:
    - uri:
        prefix: /demo2/
    rewrite:
        uri: /
    route:
    - destination:
        host: dynamodb-t1